AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

Globals:
  Function:
    Timeout: 3
    Tracing: Active
  Api:
    TracingEnabled: True

Resources:
  UpdatePricesStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: statemachine/update_all_prices.asl.json
      DefinitionSubstitutions:
        GetAssetsFunctionArn: !GetAtt GetAssetsFunction.Arn
        UpdatePricesAlphaFunctionArn: !GetAtt UpdatePricesAlphaFunction.Arn
        UpdatePricesAlphaMonthlyFunctionArn: !GetAtt UpdatePricesAlphaMonthlyFunction.Arn
        UpdateReturnsMonthlyFunctionArn: !GetAtt UpdateReturnsMonthlyFunction.Arn
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref GetAssetsFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref UpdatePricesAlphaFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref UpdatePricesAlphaMonthlyFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref UpdateReturnsMonthlyFunction

  UpdateAccountingStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: statemachine/update_all_accounting.asl.json
      DefinitionSubstitutions:
        GetAssetsFunctionArn: !GetAtt GetAssetsFunction.Arn
        UpdateAccountingFunctionArn: !GetAtt UpdateAccountingFunction.Arn
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref GetAssetsFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref UpdateAccountingFunction

  UpdateAssetsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: esgtools/
      Handler: update_assets.lambda_handler
      Runtime: python3.9
      Role: arn:aws:iam::654580413909:role/LambdaSecretsManagerReadAccess
      Timeout: 600
      MemorySize: 500
      Architectures:
        - x86_64

  GetAssetsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: esgtools/
      Handler: get_assets.lambda_handler
      Runtime: python3.9
      Role: arn:aws:iam::654580413909:role/LambdaSecretsManagerReadAccess
      Timeout: 300
      MemorySize: 500
      Architectures:
        - x86_64
      Events:
        UpdatePrices:
          Type: Api
          Properties:
            Path: /get-assets
            Method: get
  
  UpdatePricesAlphaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: esgtools/
      Handler: update_prices_alpha.lambda_handler
      Runtime: python3.9
      Role: arn:aws:iam::654580413909:role/LambdaSecretsManagerReadAccess
      Timeout: 900
      MemorySize: 1000
      Architectures:
        - x86_64

  UpdatePricesAlphaMonthlyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: esgtools/
      Handler: update_prices_alpha_monthly.lambda_handler
      Runtime: python3.9
      Role: arn:aws:iam::654580413909:role/LambdaSecretsManagerReadAccess
      Timeout: 900
      MemorySize: 1000
      Architectures:
        - x86_64

  UpdateReturnsMonthlyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: esgtools/
      Handler: update_returns_monthly.lambda_handler
      Runtime: python3.9
      Role: arn:aws:iam::654580413909:role/LambdaSecretsManagerReadAccess
      Timeout: 300
      MemorySize: 500
      Architectures:
        - x86_64

  UpdateAccountingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: esgtools/
      Handler: update_accounting.lambda_handler
      Runtime: python3.9
      Role: arn:aws:iam::654580413909:role/LambdaSecretsManagerReadAccess
      Timeout: 900
      MemorySize: 1000
      Architectures:
        - x86_64