AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Tracing: Active
  Api:
    TracingEnabled: True

Resources:
  UpdatePricesStateMachine:
    Type: AWS::Serverless::StateMachine # More info about State Machine Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-statemachine.html
    Properties:
      DefinitionUri: statemachine/update_all_prices.asl.json
      DefinitionSubstitutions:
        GetAssetsFunctionArn: !GetAtt GetAssetsFunction.Arn
        UpdatePricesFunctionArn: !GetAtt UpdatePricesFunction.Arn
      Policies: # Find out more about SAM policy templates: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html
        - LambdaInvokePolicy:
            FunctionName: !Ref GetAssetsFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref UpdatePricesFunction

  UpdateAccountingStateMachine:
    Type: AWS::Serverless::StateMachine # More info about State Machine Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-statemachine.html
    Properties:
      DefinitionUri: statemachine/update_all_accounting.asl.json
      DefinitionSubstitutions:
        GetAssetsFunctionArn: !GetAtt GetAssetsFunction.Arn
        UpdateAccountingFunctionArn: !GetAtt UpdateAccountingFunction.Arn
      Policies: # Find out more about SAM policy templates: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html
        - LambdaInvokePolicy:
            FunctionName: !Ref GetAssetsFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref UpdateAccountingFunction

  UpdateAssetsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: esgtools/
      Handler: update_assets.lambda_handler
      Runtime: python3.9
      Role: arn:aws:iam::654580413909:role/LambdaSecretsManagerReadAccess
      Timeout: 600
      MemorySize: 500
      Architectures:
        - x86_64
      Events:
        UpdateAssets:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /update-assets
            Method: get
  
  GetAssetsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: esgtools/
      Handler: get_assets.lambda_handler
      Runtime: python3.9
      Role: arn:aws:iam::654580413909:role/LambdaSecretsManagerReadAccess
      Timeout: 300
      MemorySize: 500
      Architectures:
        - x86_64
      Events:
        UpdatePrices:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /get-assets
            Method: get
  
  UpdatePricesFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: esgtools/
      Handler: update_prices.lambda_handler
      Runtime: python3.9
      Role: arn:aws:iam::654580413909:role/LambdaSecretsManagerReadAccess
      Timeout: 900
      MemorySize: 1000
      Architectures:
        - x86_64
      Events:
        UpdatePrices:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /update-prices
            Method: get

  UpdateAccountingFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: esgtools/
      Handler: update_accounting.lambda_handler
      Runtime: python3.9
      Role: arn:aws:iam::654580413909:role/LambdaSecretsManagerReadAccess
      Timeout: 900
      MemorySize: 1000
      Architectures:
        - x86_64
      Events:
        UpdatePrices:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /update-accounting
            Method: get


Outputs:
  UpdatePricesStateMachineApi:
    Description: "API Gateway endpoint URL for Prod stage for Update Assets state machine"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/update-all-prices/"
  UpdatePricesStateMachineRoleArn:
    Description: "IAM Role created for Update Prices State machine based on the specified SAM Policy Templates"
    Value: !GetAtt UpdatePricesStateMachineRole.Arn
  UpdatePricesStateMachine:
    Description: "Update Prices State Machine ARN"
    Value: !GetAtt UpdatePricesStateMachine.Arn
  UpdateAccountingStateMachineApi:
    Description: "API Gateway endpoint URL for Prod stage for Update Assets state machine"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/update-all-accounting/"
  UpdateAccountingStateMachineRoleArn:
    Description: "IAM Role created for Update Accounting State machine based on the specified SAM Policy Templates"
    Value: !GetAtt UpdateAccountingStateMachineRole.Arn
  UpdateAccountingStateMachine:
    Description: "Update Accounting State Machine ARN"
    Value: !GetAtt UpdateAccountingStateMachine.Arn
  UpdateAssetsApi:
    Description: "API Gateway endpoint URL for Prod stage for Update Assets function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/update-assets/"
  UpdateAssetsFunction:
    Description: "Update Assets Lambda Function ARN"
    Value: !GetAtt UpdateAssetsFunction.Arn
  GetAssetsApi:
    Description: "API Gateway endpoint URL for Prod stage for Get Assets function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/get-assets/"
  GetAssetsFunction:
    Description: "Get Assets Lambda Function ARN"
    Value: !GetAtt GetAssetsFunction.Arn
  UpdatePricesApi:
    Description: "API Gateway endpoint URL for Prod stage for Update Prices function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/update-prices/"
  UpdatePricesFunction:
    Description: "Update Prices Lambda Function ARN"
    Value: !GetAtt UpdatePricesFunction.Arn
